export const mems = [
  {
    title: "Scared Cat",
    upvotes: 1,
    downvotes: 2,
    img: "/images/scaredCat.jpg",
    id: 1,
  },
  {
    title: "Jack Cat",
    upvotes: 10,
    downvotes: 4,
    img: "/images/jack.jpg",
    id: 2,
  },
  {
    title: "Wife Cat",
    upvotes: 6,
    downvotes: 9,
    img: "/images/wifeCat.jpg",
    id: 3,
  },
  {
    title: "Phone Cat",
    upvotes: 6,
    downvotes: 1,
    img: "/images/phoneCat.jpg",
    id: 4,
  },
  {
    title: "Fight Cat",
    upvotes: 6,
    downvotes: 5,
    img: "/images/fightCat.jpg",
    id: 5,
  },
  {
    title: "Depressed Cat",
    upvotes: 6,
    downvotes: 2,
    img: "/images/depressedCat.jpg",
    id: 6,
  },
  {
    title: "Angry Cat",
    upvotes: 6,
    downvotes: 0,
    img: "/images/angryCat.jpg",
    id: 7,
  },
  {
    title: "Looking Cat",
    upvotes: 6,
    downvotes: 6,
    img: "/images/lookingCat.jpg",
    id: 8,
  },
];
